name: Github App Auth
description: Generate app token for subsequent commands
inputs:
  client-id:
    description: Github App Client ID
    required: true
  private-key:
    description: Github App Private Key
    required: true
outputs:
  token:
    description: Github app auth token
    value: ${{ steps.app-token.outputs.token }}
runs:
  using: composite
  steps:
  - name: Generate Github token
    uses: actions/create-github-app-token@v3
    id: app-token
    with:
      client-id: ${{ inputs.client-id }}
      private-key: ${{ inputs.private-key }}
      permission-contents: write
