name: Export build status hook
description: Generate app token for subsequent commands
inputs:
  token:
    description: API token for exporter endpoint
    required: true
  status:
    description: Job status
    required: true
runs:
  using: composite
  steps:
  - name: Post to hook-exporter
    run: ${{ github.action_path }}/exporter.sh
    shell: bash
    env:
      EXPORTER_TOKEN: ${{ inputs.token }}
      JOB_STATUS: ${{ inputs.status }}
